### ISSUE TITLE
Portfolio : Hide and  Seek

### ISSUE THREAD

**Issue by arnoldnekemiah** [badger-99/portfolio_v1.0#13]
From line 26 in your code,
you used a `display:none` property as shown below;
 `mobileContainer.style.display = 'block';`

Since you used  `display:none`  on that line, its only right you stick to the property in the else side of the code'
Your code on line 35; `mobileContainer.style.visibility = 'hidden';` :crossed_flags: 

It should be ;
`mobileContainer.style.display = 'none';` :+1:

**Comment by badger-99** [comment]
🔥 🔥 🔥  Nicely done! 💯
